# Generated by Django 5.1.3 on 2024-12-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_book_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
